Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: app.handler
      CodeUri: /Users/genie/IdeaProjects/lambda_local/hello-world
      Runtime: nodejs14.x